# Generated by Django 3.2.4 on 2021-09-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_semester_crn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('status', models.CharField(max_length=2)),
                ('department', models.CharField(max_length=4)),
                ('schedule', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting_Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.TextField()),
                ('building', models.TextField()),
                ('room_num', models.TextField()),
                ('capacity', models.IntegerField()),
                ('room_type', models.CharField(max_length=3)),
            ],
        ),
    ]
