# Generated by Django 3.2.6 on 2021-10-12 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_instructors_meeting_times_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='time',
            new_name='meet_time',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='days',
        ),
    ]
