# Generated by Django 3.2.4 on 2021-10-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20211012_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_times',
            name='end_time',
            field=models.TimeField(verbose_name='%H:%M'),
        ),
        migrations.AlterField(
            model_name='meeting_times',
            name='start_time',
            field=models.TimeField(verbose_name='%H:%M'),
        ),
    ]
