# Generated by Django 3.2.4 on 2021-10-24 16:54

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_merge_0005_auto_20211017_1536_0005_auto_20211024_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header_map',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='header_map',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='semester',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
