# Generated by Django 3.2.9 on 2021-11-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_semester_season_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='fee',
            field=models.IntegerField(blank=True),
        ),
    ]
