# Generated by Django 3.2.9 on 2021-11-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_alter_semester_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='season_year',
            field=models.TextField(default='Fall_2021'),
        ),
    ]
