# Generated by Django 3.2.4 on 2021-12-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_alter_semester_season_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='reserved',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='semester',
            name='site_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='semester',
            name='spec_appr',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
