# Generated by Django 3.2.4 on 2021-12-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_auto_20211202_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
