# Generated by Django 3.2.4 on 2021-09-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.IntegerField()),
                ('dept', models.CharField(max_length=4)),
                ('course_id', models.CharField(max_length=9)),
                ('section', models.IntegerField()),
                ('status', models.CharField(max_length=1)),
                ('title', models.TextField()),
                ('link1', models.CharField(max_length=2)),
                ('link2', models.CharField(max_length=2)),
                ('schedule_type', models.CharField(max_length=2)),
                ('reserved', models.CharField(max_length=1)),
                ('credit_hours', models.IntegerField()),
                ('billing_hours', models.IntegerField()),
                ('contact_hours', models.IntegerField()),
                ('grad_able', models.CharField(max_length=1)),
                ('cap', models.IntegerField()),
                ('waitlist_cap', models.IntegerField()),
                ('spec_appr', models.CharField(max_length=5)),
                ('meeting_type', models.CharField(max_length=5)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.CharField(max_length=8)),
                ('time', models.IntegerField()),
                ('location', models.IntegerField()),
                ('site_code', models.CharField(max_length=5)),
                ('primary_instructor', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
