# Generated by Django 3.2.4 on 2021-10-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20211017_1536'),
        ('scheduler', '0005_auto_20211024_1418'),
    ]

    operations = [
    ]
