# Generated by Django 3.2.4 on 2021-10-25 01:02

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20211024_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header_map',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='header_map',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, null=True),
        ),
    ]
