# Generated by Django 3.2.4 on 2021-10-26 20:08

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20211024_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header_map',
            name='created_date',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='header_map',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='semester',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
