# Generated by Django 3.2.4 on 2021-10-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20211026_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructors',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='semester',
            name='begin_date',
            field=models.DateField(verbose_name='%m/%d'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='semester',
            name='end_date',
            field=models.DateField(verbose_name='%m/%d'),
        ),
    ]
